[general]
hubs_server = "localhost"
reticulum_server = "localhost"
cors_proxy_server = "cors-proxy-localhost"
thumbnail_server = "nearspark-localhost"
non_cors_proxy_domains = "localhost,localhost"
base_assets_path = "/"
sentry_dsn = ""
ga_tracking_id = ""
is_moz = false

[deploy]
type = "none"
